id = "mojo-language"
name = "Mojo"
version = "0.1.0"
schema_version = 1
authors = ["Hyunjin Kim"]
description = "Mojo language support for Zed powered by tree-sitter-mojo."
repository = "https://github.com/whistlebee/zed-mojo"

[grammars.mojo]
repository = "https://github.com/whistlebee/tree-sitter-mojo"
rev = "c307dab71a43add26b4715f14e2d6de2a42e6007"


[language_servers.mojo-lsp-server]
name = "Mojo Language Server"
languages = ["Mojo"]
command = { extension = true }

[debug_adapters.mojo-lldb]
