id = "mojo-language"
name = "Mojo"
version = "0.1.0"
schema_version = 1
authors = ["Hyunjin Kim"]
description = "Mojo language support for Zed powered by tree-sitter-mojo."
repository = "https://github.com/whistlebee/zed-mojo"

[grammars.mojo]
repository = "https://github.com/whistlebee/tree-sitter-mojo"
rev = "bae96e9f412c09c3527c03f16b481b6fa6eac001"


[language_servers.mojo-lsp-server]
name = "Mojo Language Server"
languages = ["Mojo"]
command = { extension = true }

[debug_adapters.mojo-lldb]
