name = "Mojo"
grammar = "mojo"
path_suffixes = ["mojo", "🔥"]
line_comments = ["# "]
tab_size = 4
hard_tabs = false

increase_indent_pattern = "^[^#].*:\\s*(#.*)?$"
auto_indent_using_last_non_empty_line = false
decrease_indent_patterns = [
  { pattern = "^\\s*elif\\b.*:\\s*(#.*)?",    valid_after = ["if", "elif"] },
  { pattern = "^\\s*else\\b.*:\\s*(#.*)?",    valid_after = ["if", "elif", "for", "while", "except"] },
  { pattern = "^\\s*except\\b.*:\\s*(#.*)?",  valid_after = ["try", "except"] },
  { pattern = "^\\s*finally\\b.*:\\s*(#.*)?", valid_after = ["try", "except", "else"] },
]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
